spring:
  application:
    name: community
  profiles:
    active: local
  jpa:
    open-in-view: false
  autoconfigure:
    exclude: org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration
